In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/train_triplets_filtered.csv")
df

,user_id,song_id,play_count
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAPDEY12A81C210A9,1
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFNSP12AF72A0E22,1
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFOVM12A58A7D494,1
...,...,...,...
32525884,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOUHHHH12AF729E4AF,2
32525885,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOUJVIT12A8C1451C1,1
32525886,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOUSMXX12AB0185C24,1
32525887,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOWYSKH12AF72A303A,3
32525888,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOYYFLV12A58A7A88F,1

In [3]:
def play_count_to_rating(play_count):
    if play_count <= 1:
        return 1
    if play_count <= 4:
        return 2
    if play_count <= 8:
        return 3
    if play_count <= 16:
        return 4
    return 5


df["rating"] = df.play_count.apply(play_count_to_rating)
df

,user_id,song_id,play_count,rating
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAPDEY12A81C210A9,1,1
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,2
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFNSP12AF72A0E22,1,1
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFOVM12A58A7D494,1,1
...,...,...,...,...
32525884,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOUHHHH12AF729E4AF,2,2
32525885,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOUJVIT12A8C1451C1,1,1
32525886,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOUSMXX12AB0185C24,1,1
32525887,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOWYSKH12AF72A303A,3,2
32525888,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,SOYYFLV12A58A7A88F,1,1

In [4]:
df["rating"].value_counts()

1    19079587
2     8575864
3     2955538
4     1267064
5      647836
Name: rating, dtype: int64

In [5]:
df.to_csv("./data/train_triplets_filtered_ratings.csv", index=False)